2024-07-16 07:00:58,900 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO - Span: Step :transcribe
2024-07-16 07:00:58,900 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Trace ID: 307979788874814734908095523816377274425
2024-07-16 07:00:58,900 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Span ID: 1262362056486467594
2024-07-16 07:00:58,900 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Parent ID: 9843347690262622801
2024-07-16 07:00:58,900 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Start time: 2024-07-16 07:00:58.895
2024-07-16 07:00:58,900 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   End time: 2024-07-16 07:00:58.900
2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Duration: 0.005s
2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Attributes:
2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -     run_id: e7fc3fbd-91ef-4492-8252-aabdec82f712
2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -     input_name: first_args
2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -     function: transcribe_empty
2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Events:
2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -     exception at 2024-07-16 07:00:58.900 (+0.005s):
2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.type: AttributeError
2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.message: '_Span' object has no attribute 'get_attribute'
2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.stacktrace: Traceback (most recent call last):
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/trace/__init__.py", line 570, in use_span
    yield span
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/sdk/trace/__init__.py", line 1091, in start_as_current_span
    yield span
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 466, in run
    self._output = await asyncio.to_thread(self.f, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 359, in wrapper
    run_id = span.get_attribute("run_id")
           ^^^^^^^^^^^^^^^^^^
AttributeError: '_Span' object has no attribute 'get_attribute'. Did you mean: 'set_attribute'?

2024-07-16 07:00:58,901 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.escaped: False
2024-07-16 07:00:58,902 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO - 
2024-07-16 07:00:58,944 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO - Span: Pipeline :pipe
2024-07-16 07:00:58,944 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Trace ID: 307979788874814734908095523816377274425
2024-07-16 07:00:58,944 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Span ID: 9843347690262622801
2024-07-16 07:00:58,944 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Parent ID: None
2024-07-16 07:00:58,944 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Start time: 2024-07-16 07:00:58.895
2024-07-16 07:00:58,944 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   End time: 2024-07-16 07:00:58.944
2024-07-16 07:00:58,944 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Duration: 0.049s
2024-07-16 07:00:58,944 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Attributes:
2024-07-16 07:00:58,944 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -     run_id: e7fc3fbd-91ef-4492-8252-aabdec82f712
2024-07-16 07:00:58,944 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -   Events:
2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -     exception at 2024-07-16 07:00:58.904 (+0.009s):
2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.type: AttributeError
2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.message: '_Span' object has no attribute 'get_attribute'
2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.stacktrace: Traceback (most recent call last):
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 240, in start
    result = await self.run(input, run_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 266, in run
    result = await child.run(input, child.input_name, run_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 466, in run
    self._output = await asyncio.to_thread(self.f, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 359, in wrapper
    run_id = span.get_attribute("run_id")
           ^^^^^^^^^^^^^^^^^^
AttributeError: '_Span' object has no attribute 'get_attribute'. Did you mean: 'set_attribute'?

2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.escaped: False
2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -     Pipeline : pipe execution completed at 2024-07-16 07:00:58.904 (+0.009s):
2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -     No output due to exception at 2024-07-16 07:00:58.904 (+0.009s):
2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -     exception at 2024-07-16 07:00:58.944 (+0.049s):
2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.type: AttributeError
2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.message: '_Span' object has no attribute 'get_attribute'
2024-07-16 07:00:58,945 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.stacktrace: Traceback (most recent call last):
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/trace/__init__.py", line 570, in use_span
    yield span
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/sdk/trace/__init__.py", line 1091, in start_as_current_span
    yield span
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 240, in start
    result = await self.run(input, run_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 266, in run
    result = await child.run(input, child.input_name, run_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 466, in run
    self._output = await asyncio.to_thread(self.f, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 359, in wrapper
    run_id = span.get_attribute("run_id")
           ^^^^^^^^^^^^^^^^^^
AttributeError: '_Span' object has no attribute 'get_attribute'. Did you mean: 'set_attribute'?

2024-07-16 07:00:58,946 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO -       exception.escaped: False
2024-07-16 07:00:58,946 - run_e7fc3fbd-91ef-4492-8252-aabdec82f712 - INFO - 
